---
- name: Build FTP server
  hosts: node1.example.com
  tasks:
  - name: Install packages
    package:
      name: vsftpd
      state: latest

  - name: Start vsftpd service
    service: name=vsftpd enabled=true

  - name: Create README file
    copy:
      content: "Welcome to FTP server\n"
      dest: /var/ftp/pub/README
      force: no
      mode: 0444
